; --------------------------------
; Include Modern UI

!include "MUI2.nsh"

; --------------------------------
; General

; Name and output file
Name "MIRA"
!ifndef SETUP_OUTFILE
!define SETUP_OUTFILE "MIRASetup.exe"
!endif
OutFile "${SETUP_OUTFILE}"
Unicode true

; Assets and build output
!define REPO_ROOT "..\\.."
!define APP_ICON "${REPO_ROOT}\\src\\mira\\ui\\icons\\mira.ico"
!define APP_WELCOME_BITMAP "${REPO_ROOT}\\src\\mira\\ui\\icons\\setup-welcome.bmp"
!define APP_HEADER_BITMAP "${REPO_ROOT}\\src\\mira\\ui\\icons\\setup-header.bmp"
!define LICENSE_FILE "${REPO_ROOT}\\COPYING"
!define BUILD_SCRIPT "${REPO_ROOT}\\packaging\\scripts\\build_exe.sh"
!ifndef BUILD_DIR
!define BUILD_DIR "${REPO_ROOT}\\dist\\MIRA"
!endif
!define APP_EXE "MIRA.exe"
!define BUILD_EXE "${BUILD_DIR}\\${APP_EXE}"

!if /FILEEXISTS "${APP_ICON}"
	Icon "${APP_ICON}"
	UninstallIcon "${APP_ICON}"
!endif

!if /FILEEXISTS "${BUILD_EXE}"
!else
	!error "Build output not found at ${BUILD_EXE}. Run ${BUILD_SCRIPT} before compiling packaging\\windows\\setup.nsi."
!endif

!if /FILEEXISTS "${LICENSE_FILE}"
!else
	!error "License file not found at ${LICENSE_FILE}."
!endif

!if /FILEEXISTS "${APP_WELCOME_BITMAP}"
!else
	!error "Installer welcome bitmap not found at ${APP_WELCOME_BITMAP}."
!endif

!if /FILEEXISTS "${APP_HEADER_BITMAP}"
!else
	!error "Installer header bitmap not found at ${APP_HEADER_BITMAP}."
!endif

; Default installation folder
InstallDir "$LOCALAPPDATA\MIRA"

; Get installation folder from registry if available
InstallDirRegKey HKCU "Software\MIRA" ""

; Request application privileges for Windows Vista+
RequestExecutionLevel user

; --------------------------------
; Interface Settings

!define MUI_ABORTWARNING
!define MUI_ICON "${APP_ICON}"
!define MUI_UNICON "${APP_ICON}"
!define MUI_LANGDLL_REGISTRY_ROOT HKCU
!define MUI_LANGDLL_REGISTRY_KEY "Software\MIRA"
!define MUI_LANGDLL_REGISTRY_VALUENAME "InstallerLanguage"
!define MUI_HEADERIMAGE
!define MUI_HEADERIMAGE_RIGHT
!define MUI_HEADERIMAGE_BITMAP "${APP_HEADER_BITMAP}"
!define MUI_WELCOMEFINISHPAGE_BITMAP "${APP_WELCOME_BITMAP}"
BrandingText " "

; --------------------------------
; Custom language strings

LangString MIRA_LICENSE_TEXT_TOP 1033 "MIRA is free software distributed under the GNU GPL v3.0 or later. Please review the license below before installing."
LangString MIRA_LICENSE_TEXT_TOP 1034 "MIRA es software libre distribuido bajo la GNU GPL v3.0 o posterior. Revisa la licencia antes de instalar."
!define MUI_LICENSEPAGE_TEXT_TOP "$(MIRA_LICENSE_TEXT_TOP)"

LangString MIRA_SECTION_MAIN 1033 "MIRA"
LangString MIRA_SECTION_MAIN 1034 "MIRA"
LangString MIRA_SHORTCUT_UNINSTALL 1033 "Uninstall MIRA"
LangString MIRA_SHORTCUT_UNINSTALL 1034 "Desinstalar MIRA"

; --------------------------------
; Pages

!insertmacro MUI_PAGE_WELCOME
!insertmacro MUI_PAGE_LICENSE "${LICENSE_FILE}"
!insertmacro MUI_PAGE_DIRECTORY
!insertmacro MUI_PAGE_INSTFILES
!insertmacro MUI_PAGE_FINISH

!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES
!insertmacro MUI_UNPAGE_FINISH

; --------------------------------
; Languages

!insertmacro MUI_LANGUAGE "English"
!insertmacro MUI_LANGUAGE "Spanish"

!insertmacro MUI_RESERVEFILE_LANGDLL

; --------------------------------
; Language selector

Function .onInit
	!insertmacro MUI_LANGDLL_DISPLAY
FunctionEnd

; --------------------------------
; Installer Sections

Section "$(MIRA_SECTION_MAIN)" SecMain
	SetOutPath "$INSTDIR"

	; Files generated by packaging\scripts\build_exe.sh (PyInstaller onedir build)
	File /r "${BUILD_DIR}\\*"

	; Store installation folder
	WriteRegStr HKCU "Software\MIRA" "" $INSTDIR

	; Create uninstaller
	WriteUninstaller "$INSTDIR\Uninstall.exe"

	; Shortcuts
	CreateShortcut "$DESKTOP\MIRA.lnk" "$INSTDIR\${APP_EXE}" "" "$INSTDIR\${APP_EXE}" 0

	CreateDirectory "$SMPROGRAMS\MIRA"

	CreateShortcut "$SMPROGRAMS\MIRA\MIRA.lnk" "$INSTDIR\${APP_EXE}" "" "$INSTDIR\${APP_EXE}" 0

	CreateShortcut "$SMPROGRAMS\MIRA\$(MIRA_SHORTCUT_UNINSTALL).lnk" "$INSTDIR\Uninstall.exe"
SectionEnd

; --------------------------------
; Uninstaller Section

Section "Uninstall"
	; Remove shortcuts
	Delete "$DESKTOP\MIRA.lnk"
	Delete "$SMPROGRAMS\MIRA\MIRA.lnk"
	Delete "$SMPROGRAMS\MIRA\Uninstall MIRA.lnk"
	RMDir "$SMPROGRAMS\MIRA"

	; Remove installed files
	Delete "$INSTDIR\Uninstall.exe"
	RMDir /r "$INSTDIR"

	; Remove install directory and registry reference
	DeleteRegKey HKCU "Software\MIRA"
SectionEnd
